apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamingapp.fullname" . }}-secret
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.app.jwtSecret | quote }}
